/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentOperator"
      | "approvedRecipients"
      | "approvedRecipientsList"
      | "batchSend"
      | "configureAutoStream"
      | "deposit"
      | "getApprovedRecipients"
      | "getBalance"
      | "getStats"
      | "initiateStream"
      | "owner"
      | "paymentLimits"
      | "paymentStreamContract"
      | "renounceOwnership"
      | "sendPayment"
      | "setDailyLimit"
      | "setOperator"
      | "totalReceived"
      | "totalSent"
      | "transferOwnership"
      | "usdt"
      | "withdraw"
      | "withdrawAll"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoStreamConfigured"
      | "FundsReceived"
      | "FundsSent"
      | "OwnershipTransferred"
      | "PaymentLimitUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvedRecipients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedRecipientsList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSend",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "configureAutoStream",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedRecipients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initiateStream",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentLimits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paymentStreamContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendPayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReceived",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalSent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "agentOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedRecipientsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configureAutoStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentStreamContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalSent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
}

export namespace AutoStreamConfiguredEvent {
  export type InputTuple = [
    recipient: AddressLike,
    maxAmount: BigNumberish,
    maxDuration: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    maxAmount: bigint,
    maxDuration: bigint
  ];
  export interface OutputObject {
    recipient: string;
    maxAmount: bigint;
    maxDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsSentEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentWallet extends BaseContract {
  connect(runner?: ContractRunner | null): AgentWallet;
  waitForDeployment(): Promise<this>;

  interface: AgentWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentOperator: TypedContractMethod<[], [string], "view">;

  approvedRecipients: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        recipient: string;
        maxAmount: bigint;
        maxDuration: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  approvedRecipientsList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  batchSend: TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  configureAutoStream: TypedContractMethod<
    [
      recipient: AddressLike,
      maxAmount: BigNumberish,
      maxDuration: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getApprovedRecipients: TypedContractMethod<[], [string[]], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        balance: bigint;
        received: bigint;
        sent: bigint;
        remainingDaily: bigint;
      }
    ],
    "view"
  >;

  initiateStream: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, duration: BigNumberish],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentLimits: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        dailyLimit: bigint;
        spentToday: bigint;
        lastResetDay: bigint;
      }
    ],
    "view"
  >;

  paymentStreamContract: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendPayment: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  totalReceived: TypedContractMethod<[], [bigint], "view">;

  totalSent: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawAll: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentOperator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approvedRecipients"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        recipient: string;
        maxAmount: bigint;
        maxDuration: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approvedRecipientsList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batchSend"
  ): TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureAutoStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      maxAmount: BigNumberish,
      maxDuration: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApprovedRecipients"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        balance: bigint;
        received: bigint;
        sent: bigint;
        remainingDaily: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateStream"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, duration: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentLimits"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        dailyLimit: bigint;
        spentToday: bigint;
        lastResetDay: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentStreamContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendPayment"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDailyLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalReceived"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawAll"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AutoStreamConfigured"
  ): TypedContractEvent<
    AutoStreamConfiguredEvent.InputTuple,
    AutoStreamConfiguredEvent.OutputTuple,
    AutoStreamConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "FundsReceived"
  ): TypedContractEvent<
    FundsReceivedEvent.InputTuple,
    FundsReceivedEvent.OutputTuple,
    FundsReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsSent"
  ): TypedContractEvent<
    FundsSentEvent.InputTuple,
    FundsSentEvent.OutputTuple,
    FundsSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentLimitUpdated"
  ): TypedContractEvent<
    PaymentLimitUpdatedEvent.InputTuple,
    PaymentLimitUpdatedEvent.OutputTuple,
    PaymentLimitUpdatedEvent.OutputObject
  >;

  filters: {
    "AutoStreamConfigured(address,uint256,uint256)": TypedContractEvent<
      AutoStreamConfiguredEvent.InputTuple,
      AutoStreamConfiguredEvent.OutputTuple,
      AutoStreamConfiguredEvent.OutputObject
    >;
    AutoStreamConfigured: TypedContractEvent<
      AutoStreamConfiguredEvent.InputTuple,
      AutoStreamConfiguredEvent.OutputTuple,
      AutoStreamConfiguredEvent.OutputObject
    >;

    "FundsReceived(address,uint256)": TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;
    FundsReceived: TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;

    "FundsSent(address,uint256)": TypedContractEvent<
      FundsSentEvent.InputTuple,
      FundsSentEvent.OutputTuple,
      FundsSentEvent.OutputObject
    >;
    FundsSent: TypedContractEvent<
      FundsSentEvent.InputTuple,
      FundsSentEvent.OutputTuple,
      FundsSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentLimitUpdated(uint256)": TypedContractEvent<
      PaymentLimitUpdatedEvent.InputTuple,
      PaymentLimitUpdatedEvent.OutputTuple,
      PaymentLimitUpdatedEvent.OutputObject
    >;
    PaymentLimitUpdated: TypedContractEvent<
      PaymentLimitUpdatedEvent.InputTuple,
      PaymentLimitUpdatedEvent.OutputTuple,
      PaymentLimitUpdatedEvent.OutputObject
    >;
  };
}
