/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BillingRegistry {
  export type UsageRecordStruct = {
    serviceId: BytesLike;
    consumer: AddressLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    amountPaid: BigNumberish;
    isStream: boolean;
  };

  export type UsageRecordStructOutput = [
    serviceId: string,
    consumer: string,
    startTime: bigint,
    endTime: bigint,
    amountPaid: bigint,
    isStream: boolean
  ] & {
    serviceId: string;
    consumer: string;
    startTime: bigint;
    endTime: bigint;
    amountPaid: bigint;
    isStream: boolean;
  };

  export type ServiceStruct = {
    serviceId: BytesLike;
    provider: AddressLike;
    name: string;
    description: string;
    endpoint: string;
    billingType: BigNumberish;
    rate: BigNumberish;
    minDuration: BigNumberish;
    maxDuration: BigNumberish;
    isActive: boolean;
    totalEarned: BigNumberish;
    totalRequests: BigNumberish;
    ratingSum: BigNumberish;
    ratingCount: BigNumberish;
    tags: string[];
  };

  export type ServiceStructOutput = [
    serviceId: string,
    provider: string,
    name: string,
    description: string,
    endpoint: string,
    billingType: bigint,
    rate: bigint,
    minDuration: bigint,
    maxDuration: bigint,
    isActive: boolean,
    totalEarned: bigint,
    totalRequests: bigint,
    ratingSum: bigint,
    ratingCount: bigint,
    tags: string[]
  ] & {
    serviceId: string;
    provider: string;
    name: string;
    description: string;
    endpoint: string;
    billingType: bigint;
    rate: bigint;
    minDuration: bigint;
    maxDuration: bigint;
    isActive: boolean;
    totalEarned: bigint;
    totalRequests: bigint;
    ratingSum: bigint;
    ratingCount: bigint;
    tags: string[];
  };
}

export interface BillingRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeServiceIds"
      | "calculateCost"
      | "consumerHistory"
      | "getActiveServices"
      | "getAverageRating"
      | "getConsumerHistory"
      | "getMarketplaceStats"
      | "getProviderServices"
      | "getService"
      | "getServicesByTag"
      | "minServiceRate"
      | "owner"
      | "paymentStreamContract"
      | "platformFeeBps"
      | "providerEarnings"
      | "providerServices"
      | "rateService"
      | "recordConsumption"
      | "registerService"
      | "renounceOwnership"
      | "searchServices"
      | "services"
      | "setMinServiceRate"
      | "setPaymentStreamContract"
      | "standardServices"
      | "tagIndex"
      | "totalServices"
      | "transferOwnership"
      | "updateService"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentStreamContractUpdated"
      | "ServiceConsumed"
      | "ServiceRated"
      | "ServiceRegistered"
      | "ServiceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeServiceIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCost",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumerHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveServices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageRating",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsumerHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderServices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getService",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getServicesByTag",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "minServiceRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentStreamContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "providerServices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateService",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordConsumption",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerService",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "searchServices",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "services", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setMinServiceRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentStreamContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "standardServices",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tagIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalServices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateService",
    values: [BytesLike, BigNumberish, boolean, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeServiceIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumerHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConsumerHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getService", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getServicesByTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minServiceRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentStreamContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordConsumption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "searchServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "services", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinServiceRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentStreamContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "standardServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tagIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateService",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentStreamContractUpdatedEvent {
  export type InputTuple = [newContract: AddressLike];
  export type OutputTuple = [newContract: string];
  export interface OutputObject {
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceConsumedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    consumer: AddressLike,
    amount: BigNumberish,
    isStream: boolean
  ];
  export type OutputTuple = [
    serviceId: string,
    consumer: string,
    amount: bigint,
    isStream: boolean
  ];
  export interface OutputObject {
    serviceId: string;
    consumer: string;
    amount: bigint;
    isStream: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRatedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    consumer: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    consumer: string,
    rating: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    consumer: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRegisteredEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    provider: AddressLike,
    name: string,
    billingType: BigNumberish,
    rate: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    provider: string,
    name: string,
    billingType: bigint,
    rate: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    provider: string;
    name: string;
    billingType: bigint;
    rate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceUpdatedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    newRate: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    serviceId: string,
    newRate: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    serviceId: string;
    newRate: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BillingRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BillingRegistry;
  waitForDeployment(): Promise<this>;

  interface: BillingRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeServiceIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  calculateCost: TypedContractMethod<
    [serviceId: BytesLike, durationOrQuantity: BigNumberish],
    [bigint],
    "view"
  >;

  consumerHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        serviceId: string;
        consumer: string;
        startTime: bigint;
        endTime: bigint;
        amountPaid: bigint;
        isStream: boolean;
      }
    ],
    "view"
  >;

  getActiveServices: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getAverageRating: TypedContractMethod<
    [serviceId: BytesLike],
    [bigint],
    "view"
  >;

  getConsumerHistory: TypedContractMethod<
    [consumer: AddressLike],
    [BillingRegistry.UsageRecordStructOutput[]],
    "view"
  >;

  getMarketplaceStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalServices: bigint;
        totalVolume: bigint;
        totalProviders: bigint;
      }
    ],
    "view"
  >;

  getProviderServices: TypedContractMethod<
    [provider: AddressLike],
    [string[]],
    "view"
  >;

  getService: TypedContractMethod<
    [serviceId: BytesLike],
    [BillingRegistry.ServiceStructOutput],
    "view"
  >;

  getServicesByTag: TypedContractMethod<[tag: string], [string[]], "view">;

  minServiceRate: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentStreamContract: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  providerEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  providerServices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  rateService: TypedContractMethod<
    [serviceId: BytesLike, rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordConsumption: TypedContractMethod<
    [
      serviceId: BytesLike,
      consumer: AddressLike,
      amount: BigNumberish,
      isStream: boolean,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerService: TypedContractMethod<
    [
      name: string,
      description: string,
      endpoint: string,
      billingType: BigNumberish,
      rate: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish,
      tags: string[]
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  searchServices: TypedContractMethod<[keyword: string], [string[]], "view">;

  services: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        serviceId: string;
        provider: string;
        name: string;
        description: string;
        endpoint: string;
        billingType: bigint;
        rate: bigint;
        minDuration: bigint;
        maxDuration: bigint;
        isActive: boolean;
        totalEarned: bigint;
        totalRequests: bigint;
        ratingSum: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  setMinServiceRate: TypedContractMethod<
    [newMin: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentStreamContract: TypedContractMethod<
    [_contract: AddressLike],
    [void],
    "nonpayable"
  >;

  standardServices: TypedContractMethod<[arg0: string], [string], "view">;

  tagIndex: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  totalServices: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateService: TypedContractMethod<
    [
      serviceId: BytesLike,
      newRate: BigNumberish,
      isActive: boolean,
      newDescription: string,
      newEndpoint: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeServiceIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "calculateCost"
  ): TypedContractMethod<
    [serviceId: BytesLike, durationOrQuantity: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "consumerHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        serviceId: string;
        consumer: string;
        startTime: bigint;
        endTime: bigint;
        amountPaid: bigint;
        isStream: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveServices"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAverageRating"
  ): TypedContractMethod<[serviceId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getConsumerHistory"
  ): TypedContractMethod<
    [consumer: AddressLike],
    [BillingRegistry.UsageRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketplaceStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalServices: bigint;
        totalVolume: bigint;
        totalProviders: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderServices"
  ): TypedContractMethod<[provider: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getService"
  ): TypedContractMethod<
    [serviceId: BytesLike],
    [BillingRegistry.ServiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getServicesByTag"
  ): TypedContractMethod<[tag: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "minServiceRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentStreamContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerServices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "rateService"
  ): TypedContractMethod<
    [serviceId: BytesLike, rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordConsumption"
  ): TypedContractMethod<
    [
      serviceId: BytesLike,
      consumer: AddressLike,
      amount: BigNumberish,
      isStream: boolean,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerService"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      endpoint: string,
      billingType: BigNumberish,
      rate: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish,
      tags: string[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "searchServices"
  ): TypedContractMethod<[keyword: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "services"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        serviceId: string;
        provider: string;
        name: string;
        description: string;
        endpoint: string;
        billingType: bigint;
        rate: bigint;
        minDuration: bigint;
        maxDuration: bigint;
        isActive: boolean;
        totalEarned: bigint;
        totalRequests: bigint;
        ratingSum: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMinServiceRate"
  ): TypedContractMethod<[newMin: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentStreamContract"
  ): TypedContractMethod<[_contract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "standardServices"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "tagIndex"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalServices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateService"
  ): TypedContractMethod<
    [
      serviceId: BytesLike,
      newRate: BigNumberish,
      isActive: boolean,
      newDescription: string,
      newEndpoint: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentStreamContractUpdated"
  ): TypedContractEvent<
    PaymentStreamContractUpdatedEvent.InputTuple,
    PaymentStreamContractUpdatedEvent.OutputTuple,
    PaymentStreamContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceConsumed"
  ): TypedContractEvent<
    ServiceConsumedEvent.InputTuple,
    ServiceConsumedEvent.OutputTuple,
    ServiceConsumedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRated"
  ): TypedContractEvent<
    ServiceRatedEvent.InputTuple,
    ServiceRatedEvent.OutputTuple,
    ServiceRatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRegistered"
  ): TypedContractEvent<
    ServiceRegisteredEvent.InputTuple,
    ServiceRegisteredEvent.OutputTuple,
    ServiceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ServiceUpdated"
  ): TypedContractEvent<
    ServiceUpdatedEvent.InputTuple,
    ServiceUpdatedEvent.OutputTuple,
    ServiceUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentStreamContractUpdated(address)": TypedContractEvent<
      PaymentStreamContractUpdatedEvent.InputTuple,
      PaymentStreamContractUpdatedEvent.OutputTuple,
      PaymentStreamContractUpdatedEvent.OutputObject
    >;
    PaymentStreamContractUpdated: TypedContractEvent<
      PaymentStreamContractUpdatedEvent.InputTuple,
      PaymentStreamContractUpdatedEvent.OutputTuple,
      PaymentStreamContractUpdatedEvent.OutputObject
    >;

    "ServiceConsumed(bytes32,address,uint256,bool)": TypedContractEvent<
      ServiceConsumedEvent.InputTuple,
      ServiceConsumedEvent.OutputTuple,
      ServiceConsumedEvent.OutputObject
    >;
    ServiceConsumed: TypedContractEvent<
      ServiceConsumedEvent.InputTuple,
      ServiceConsumedEvent.OutputTuple,
      ServiceConsumedEvent.OutputObject
    >;

    "ServiceRated(bytes32,address,uint8)": TypedContractEvent<
      ServiceRatedEvent.InputTuple,
      ServiceRatedEvent.OutputTuple,
      ServiceRatedEvent.OutputObject
    >;
    ServiceRated: TypedContractEvent<
      ServiceRatedEvent.InputTuple,
      ServiceRatedEvent.OutputTuple,
      ServiceRatedEvent.OutputObject
    >;

    "ServiceRegistered(bytes32,address,string,uint8,uint256)": TypedContractEvent<
      ServiceRegisteredEvent.InputTuple,
      ServiceRegisteredEvent.OutputTuple,
      ServiceRegisteredEvent.OutputObject
    >;
    ServiceRegistered: TypedContractEvent<
      ServiceRegisteredEvent.InputTuple,
      ServiceRegisteredEvent.OutputTuple,
      ServiceRegisteredEvent.OutputObject
    >;

    "ServiceUpdated(bytes32,uint256,bool)": TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;
    ServiceUpdated: TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;
  };
}
