/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaymentStream {
  export type StreamStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    depositAmount: BigNumberish;
    withdrawnAmount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    ratePerSecond: BigNumberish;
    isActive: boolean;
    serviceId: string;
  };

  export type StreamStructOutput = [
    sender: string,
    recipient: string,
    depositAmount: bigint,
    withdrawnAmount: bigint,
    startTime: bigint,
    endTime: bigint,
    ratePerSecond: bigint,
    isActive: boolean,
    serviceId: string
  ] & {
    sender: string;
    recipient: string;
    depositAmount: bigint;
    withdrawnAmount: bigint;
    startTime: bigint;
    endTime: bigint;
    ratePerSecond: bigint;
    isActive: boolean;
    serviceId: string;
  };
}

export interface PaymentStreamInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_STREAM_DURATION"
      | "MIN_STREAM_DURATION"
      | "availableBalance"
      | "cancelStream"
      | "createStream"
      | "feeRecipient"
      | "getRecipientStreams"
      | "getSenderStreams"
      | "getStream"
      | "getTotalValueLocked"
      | "owner"
      | "platformFeeBps"
      | "recipientStreams"
      | "renounceOwnership"
      | "senderStreams"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "streamCount"
      | "streams"
      | "transferOwnership"
      | "usdt"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "StreamCancelled"
      | "StreamCompleted"
      | "StreamCreated"
      | "StreamWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_STREAM_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STREAM_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSenderStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValueLocked",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipientStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "senderStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "streams", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "MAX_STREAM_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STREAM_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSenderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "senderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    streamId: BytesLike,
    sender: AddressLike,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    sender: string,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    streamId: string;
    sender: string;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCompletedEvent {
  export type InputTuple = [streamId: BytesLike];
  export type OutputTuple = [streamId: string];
  export interface OutputObject {
    streamId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    streamId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    serviceId: string
  ];
  export type OutputTuple = [
    streamId: string,
    sender: string,
    recipient: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint,
    serviceId: string
  ];
  export interface OutputObject {
    streamId: string;
    sender: string;
    recipient: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
    serviceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    streamId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    streamId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentStream extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentStream;
  waitForDeployment(): Promise<this>;

  interface: PaymentStreamInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_STREAM_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_STREAM_DURATION: TypedContractMethod<[], [bigint], "view">;

  availableBalance: TypedContractMethod<
    [streamId: BytesLike],
    [bigint],
    "view"
  >;

  cancelStream: TypedContractMethod<
    [streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  createStream: TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      duration: BigNumberish,
      serviceId: string
    ],
    [string],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getRecipientStreams: TypedContractMethod<
    [recipient: AddressLike],
    [string[]],
    "view"
  >;

  getSenderStreams: TypedContractMethod<
    [sender: AddressLike],
    [string[]],
    "view"
  >;

  getStream: TypedContractMethod<
    [streamId: BytesLike],
    [PaymentStream.StreamStructOutput],
    "view"
  >;

  getTotalValueLocked: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  recipientStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  senderStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  setFeeRecipient: TypedContractMethod<
    [newFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  streamCount: TypedContractMethod<[], [bigint], "view">;

  streams: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        isActive: boolean;
        serviceId: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_STREAM_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STREAM_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableBalance"
  ): TypedContractMethod<[streamId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      duration: BigNumberish,
      serviceId: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRecipientStreams"
  ): TypedContractMethod<[recipient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSenderStreams"
  ): TypedContractMethod<[sender: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStream"
  ): TypedContractMethod<
    [streamId: BytesLike],
    [PaymentStream.StreamStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalValueLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipientStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "senderStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newFeeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        isActive: boolean;
        serviceId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamCompleted"
  ): TypedContractEvent<
    StreamCompletedEvent.InputTuple,
    StreamCompletedEvent.OutputTuple,
    StreamCompletedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StreamCancelled(bytes32,address,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamCompleted(bytes32)": TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;
    StreamCompleted: TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;

    "StreamCreated(bytes32,address,address,uint256,uint256,uint256,string)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
  };
}
